"""
File system tools for agents.
All operations are sandboxed to PROJECT_ROOT — agents cannot escape.
"""
import os
import glob
from typing import Any
from pathlib import Path
from langchain_core.tools import tool
from config import PROJECT_ROOT, MAX_FILE_READ_BYTES


def _safe_path(path_str: str) -> Path:
    """
    Resolve a path and ensure it's within PROJECT_ROOT.
    Raises ValueError if the path escapes the sandbox.
    """
    # Allow both absolute and relative paths
    p = Path(path_str)
    if not p.is_absolute():
        p = PROJECT_ROOT / p
    resolved = p.resolve()

    # Security check: must be inside PROJECT_ROOT
    try:
        resolved.relative_to(PROJECT_ROOT.resolve())
    except ValueError:
        raise ValueError(
            f"Access denied: '{path_str}' resolves to '{resolved}' "
            f"which is outside PROJECT_ROOT '{PROJECT_ROOT}'"
        )
    return resolved


@tool
def read_file(path: str) -> str:
    """Read the contents of a file. Path can be relative to project root or absolute."""
    resolved = _safe_path(path)
    if not resolved.exists():
        return f"Error: File not found: {resolved}"
    if not resolved.is_file():
        return f"Error: Not a file: {resolved}"

    size = resolved.stat().st_size
    if size > MAX_FILE_READ_BYTES:
        return (
            f"Error: File too large ({size:,} bytes). "
            f"Max allowed: {MAX_FILE_READ_BYTES:,} bytes. "
            f"Use search_files to find specific content instead."
        )

    try:
        content = resolved.read_text(encoding="utf-8")
    except UnicodeDecodeError:
        return f"Error: Cannot read binary file: {resolved}"

    # Add line numbers for context
    lines = content.splitlines()
    numbered = "\n".join(f"{i+1:4d} | {line}" for i, line in enumerate(lines))
    return f"File: {resolved}\nLines: {len(lines)}\n\n{numbered}"


# Config files that should not be overwritten after scaffolding.
# These are generated by create-next-app / create-vite / etc. and
# must stay intact. Agents can edit_file to modify specific sections,
# but write_file (full overwrite) is blocked.
_PROTECTED_FILES = {
    "tsconfig.json", "next.config.ts", "next.config.js", "next.config.mjs",
    "postcss.config.mjs", "postcss.config.js", "tailwind.config.ts",
    "tailwind.config.js", "eslint.config.mjs", "eslint.config.js",
    "vite.config.ts", "vite.config.js",
    "package-lock.json",
}


@tool
def write_file(path: str, content: Any) -> str:
    """Write content to a file. Creates parent directories if needed. Overwrites existing files.
    Content can be a string or a JSON object (dict/list) — JSON objects are auto-serialized."""
    import json as _json
    from tools.hooks import get_current_agent, check_write_scope, validate_content

    resolved = _safe_path(path)

    # ── Agent write scope check ──────────────────────────────────
    agent = get_current_agent()
    if agent:
        scope_error = check_write_scope(agent, path)
        if scope_error:
            return scope_error

    # Block full overwrites of scaffolded config files
    if resolved.exists() and resolved.name in _PROTECTED_FILES:
        return (
            f"Error: '{resolved.name}' is a protected config file that was generated "
            f"by the project scaffolding tool. Do NOT overwrite it. "
            f"If you need to modify it, use edit_file to change specific sections. "
            f"If you need to add dependencies, use npm_install instead."
        )

    resolved.parent.mkdir(parents=True, exist_ok=True)

    # If the model passed a dict/list, handle based on file extension:
    # - For .json files: serialize as proper JSON (this is the correct format)
    # - For code files (.ts, .tsx, .js, etc.): reject and tell agent to pass a string
    if isinstance(content, (dict, list)):
        if resolved.suffix == ".json":
            content = _json.dumps(content, indent=2, ensure_ascii=False)
        else:
            return (
                f"Error: write_file received a JSON object for '{resolved.name}' "
                f"but this is not a .json file. For code files (.ts, .tsx, .js, etc.), "
                f"pass the content as a STRING containing the actual source code, "
                f"not as a JSON object. Example: content='import mongoose from \"mongoose\";\\n...'"
            )
    elif not isinstance(content, str):
        content = str(content)

    # ── Pre-write validation hooks ───────────────────────────────
    validation_error = validate_content(path, content)
    if validation_error:
        return validation_error

    resolved.write_text(content, encoding="utf-8")
    lines = content.count("\n") + 1
    return f"Written {lines} lines to {resolved}"


@tool
def append_file(path: str, content: str) -> str:
    """Append content to the end of an existing file."""
    resolved = _safe_path(path)
    if not resolved.exists():
        return f"Error: File not found: {resolved}. Use write_file to create it first."
    with open(resolved, "a", encoding="utf-8") as f:
        f.write(content)
    return f"Appended {len(content)} chars to {resolved}"


@tool
def list_directory(path: str = ".") -> str:
    """List files and directories at the given path. Shows type, size, and name."""
    resolved = _safe_path(path)
    if not resolved.exists():
        return f"Error: Directory not found: {resolved}"
    if not resolved.is_dir():
        return f"Error: Not a directory: {resolved}"

    entries = sorted(resolved.iterdir(), key=lambda e: (not e.is_dir(), e.name.lower()))
    lines = []
    for entry in entries:
        if entry.name.startswith(".") and entry.name not in (".env", ".gitignore"):
            continue  # Skip hidden files except useful ones
        if entry.is_dir():
            child_count = sum(1 for _ in entry.rglob("*") if _.is_file())
            lines.append(f"  📁 {entry.name}/  ({child_count} files)")
        else:
            size = entry.stat().st_size
            if size < 1024:
                size_str = f"{size} B"
            elif size < 1024 * 1024:
                size_str = f"{size / 1024:.1f} KB"
            else:
                size_str = f"{size / (1024*1024):.1f} MB"
            lines.append(f"  📄 {entry.name}  ({size_str})")

    header = f"Directory: {resolved}\nEntries: {len(lines)}\n"
    return header + "\n".join(lines) if lines else header + "  (empty)"


@tool
def search_files(pattern: str, path: str = ".", file_glob: str = "**/*") -> str:
    """
    Search for a text pattern in files under the given path.
    Args:
        pattern: Text to search for (case-insensitive)
        path: Directory to search in (relative to project root or absolute)
        file_glob: Glob pattern to filter files (default: all files)
    Returns matching lines with file paths and line numbers.
    """
    resolved = _safe_path(path)
    if not resolved.is_dir():
        return f"Error: Not a directory: {resolved}"

    results = []
    max_results = 50
    pattern_lower = pattern.lower()

    for filepath in resolved.glob(file_glob):
        if not filepath.is_file():
            continue
        # Skip binary files, node_modules, .git, __pycache__, venv
        skip_dirs = {".git", "node_modules", "__pycache__", ".venv", "venv", "chromadb_data"}
        if any(part in skip_dirs for part in filepath.parts):
            continue
        if filepath.stat().st_size > MAX_FILE_READ_BYTES:
            continue

        try:
            text = filepath.read_text(encoding="utf-8")
        except (UnicodeDecodeError, PermissionError):
            continue

        for line_num, line in enumerate(text.splitlines(), 1):
            if pattern_lower in line.lower():
                rel = filepath.relative_to(resolved)
                results.append(f"  {rel}:{line_num}  {line.strip()}")
                if len(results) >= max_results:
                    return (
                        f"Search: '{pattern}' in {resolved}\n"
                        f"Results: {len(results)} (capped at {max_results})\n\n"
                        + "\n".join(results)
                    )

    if not results:
        return f"Search: '{pattern}' in {resolved}\nNo matches found."

    return (
        f"Search: '{pattern}' in {resolved}\n"
        f"Results: {len(results)}\n\n"
        + "\n".join(results)
    )


@tool
def edit_file(path: str, old_content: str, new_content: str) -> str:
    """Replace a specific section of a file. Finds old_content and replaces it with new_content.
    Use this to modify existing files without rewriting the whole thing.
    Args:
        path: File path (relative to project root or absolute)
        old_content: The exact text to find and replace (must match exactly, including whitespace)
        new_content: The replacement text
    """
    from tools.hooks import get_current_agent, check_write_scope

    resolved = _safe_path(path)

    # ── Agent write scope check ──────────────────────────────────
    agent = get_current_agent()
    if agent:
        scope_error = check_write_scope(agent, path)
        if scope_error:
            return scope_error

    if not resolved.exists():
        return f"Error: File not found: {resolved}"
    if not resolved.is_file():
        return f"Error: Not a file: {resolved}"

    try:
        text = resolved.read_text(encoding="utf-8")
    except UnicodeDecodeError:
        return f"Error: Cannot read binary file: {resolved}"

    if old_content not in text:
        # Show nearby content to help the agent find the right string
        lines = text.splitlines()
        preview = "\n".join(lines[:30]) if len(lines) > 30 else text
        return (
            f"Error: old_content not found in {resolved}.\n"
            f"First 30 lines of file:\n{preview}"
        )

    new_text = text.replace(old_content, new_content, 1)

    # ── Validate the resulting file content ──────────────────────
    from tools.hooks import validate_content
    validation_error = validate_content(path, new_text)
    if validation_error:
        return validation_error

    resolved.write_text(new_text, encoding="utf-8")

    old_lines = old_content.count("\n") + 1
    new_lines = new_content.count("\n") + 1
    return f"Edited {resolved}: replaced {old_lines} lines with {new_lines} lines"


@tool
def create_directory(path: str) -> str:
    """Create a directory (and any parent directories)."""
    from tools.hooks import get_current_agent, check_write_scope

    resolved = _safe_path(path)

    # Agent write scope check (directory creation = implicit write)
    agent = get_current_agent()
    if agent:
        scope_error = check_write_scope(agent, path + "/")
        if scope_error:
            return scope_error

    resolved.mkdir(parents=True, exist_ok=True)
    return f"Created directory: {resolved}"


# ── Reference project tools (read-only access to v1 codebase) ────
from config import REFERENCE_PROJECT_ROOT


def _safe_ref_path(path_str: str) -> Path:
    """Resolve a path within the reference project root (read-only)."""
    if not REFERENCE_PROJECT_ROOT:
        raise ValueError("No reference project configured. Set REFERENCE_PROJECT_ROOT in .env")
    p = Path(path_str)
    if not p.is_absolute():
        p = REFERENCE_PROJECT_ROOT / p
    resolved = p.resolve()
    try:
        resolved.relative_to(REFERENCE_PROJECT_ROOT.resolve())
    except ValueError:
        raise ValueError(f"Access denied: '{path_str}' is outside reference project")
    return resolved


@tool
def read_reference_file(path: str) -> str:
    """Read a file from the REFERENCE project (v1 codebase). Read-only — use this to
    understand how the existing app works before building v2.
    Args:
        path: File path relative to the reference project root
    """
    try:
        resolved = _safe_ref_path(path)
    except ValueError as e:
        return str(e)
    if not resolved.exists():
        # Suggest listing the parent directory to discover actual files
        parent = resolved.parent
        hint = ""
        if parent.exists():
            siblings = [f.name for f in parent.iterdir() if f.is_file()][:10]
            if siblings:
                hint = f"\nFiles in {parent.name}/: {', '.join(siblings)}"
        return (
            f"Error: File not found: {resolved}.{hint}\n"
            f"TIP: Use list_reference_directory to explore the project structure first."
        )
    if not resolved.is_file():
        return f"Error: Not a file: {resolved}"

    size = resolved.stat().st_size
    if size > MAX_FILE_READ_BYTES:
        return f"Error: File too large ({size:,} bytes)"

    try:
        content = resolved.read_text(encoding="utf-8")
    except UnicodeDecodeError:
        return f"Error: Cannot read binary file: {resolved}"

    lines = content.splitlines()
    numbered = "\n".join(f"{i+1:4d} | {line}" for i, line in enumerate(lines))
    return f"Reference file: {resolved}\nLines: {len(lines)}\n\n{numbered}"


@tool
def list_reference_directory(path: str = ".") -> str:
    """List files in the REFERENCE project (v1 codebase). Read-only.
    Use this to explore the existing app structure before building v2.
    Args:
        path: Directory path relative to the reference project root
    """
    try:
        resolved = _safe_ref_path(path)
    except ValueError as e:
        return str(e)
    if not resolved.exists():
        return f"Error: Directory not found in reference project: {resolved}"
    if not resolved.is_dir():
        return f"Error: Not a directory: {resolved}"

    entries = sorted(resolved.iterdir(), key=lambda e: (not e.is_dir(), e.name.lower()))
    lines = []
    for entry in entries:
        if entry.name.startswith(".") and entry.name not in (".env", ".gitignore"):
            continue
        if entry.name in ("node_modules", ".git", "__pycache__", ".next", "dist", "build"):
            continue
        if entry.is_dir():
            lines.append(f"  [dir] {entry.name}/")
        else:
            size = entry.stat().st_size
            size_str = f"{size} B" if size < 1024 else f"{size/1024:.1f} KB"
            lines.append(f"  [file] {entry.name}  ({size_str})")

    header = f"Reference directory: {resolved}\nEntries: {len(lines)}\n"
    return header + "\n".join(lines) if lines else header + "  (empty)"


@tool
def search_reference_files(pattern: str, path: str = ".", file_glob: str = "**/*") -> str:
    """Search for text in the REFERENCE project (v1 codebase). Read-only.
    Use this to find how v1 implements a specific feature.
    Args:
        pattern: Text to search for (case-insensitive)
        path: Directory to search in (relative to reference project root)
        file_glob: Glob pattern to filter files
    """
    try:
        resolved = _safe_ref_path(path)
    except ValueError as e:
        return str(e)
    if not resolved.is_dir():
        return f"Error: Not a directory: {resolved}"

    results = []
    max_results = 30
    pattern_lower = pattern.lower()
    skip_dirs = {".git", "node_modules", "__pycache__", ".venv", ".next", "dist", "build"}

    for filepath in resolved.glob(file_glob):
        if not filepath.is_file():
            continue
        if any(part in skip_dirs for part in filepath.parts):
            continue
        if filepath.stat().st_size > MAX_FILE_READ_BYTES:
            continue
        try:
            text = filepath.read_text(encoding="utf-8")
        except (UnicodeDecodeError, PermissionError):
            continue
        for line_num, line in enumerate(text.splitlines(), 1):
            if pattern_lower in line.lower():
                rel = filepath.relative_to(resolved)
                results.append(f"  {rel}:{line_num}  {line.strip()}")
                if len(results) >= max_results:
                    break
        if len(results) >= max_results:
            break

    if not results:
        return f"Search: '{pattern}' in reference project {resolved}\nNo matches found."
    return (
        f"Search: '{pattern}' in reference project {resolved}\n"
        f"Results: {len(results)}\n\n"
        + "\n".join(results)
    )


# Conditionally include reference tools only if a reference project is configured
REFERENCE_TOOLS = []
if REFERENCE_PROJECT_ROOT and REFERENCE_PROJECT_ROOT.exists():
    REFERENCE_TOOLS = [read_reference_file, list_reference_directory, search_reference_files]


# Export all file tools as a list for easy registration
FILE_TOOLS = [read_file, write_file, edit_file, append_file, list_directory, search_files, create_directory]
